services:
  ollama:
    image: ollama/ollama:latest
    container_name: quiz-ollama
    ports:
      - '11434:11434'
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_NUM_PARALLEL=2
      - OLLAMA_MAX_LOADED_MODELS=1
      - OLLAMA_FLASH_ATTENTION=1
      - OLLAMA_GPU_LAYERS=999
      - OLLAMA_VRAM_FRACTION=0.8
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
          memory: 4G
    healthcheck:
      test: ['CMD', 'ollama', 'list']
      interval: 60s
      timeout: 30s
      retries: 10
      start_period: 300s
    networks:
      - quiz-network
  piston:
    image: ghcr.io/engineer-man/piston
    container_name: quiz-piston
    ports:
      - '2000:2000'
    restart: unless-stopped
    privileged: true
    environment:
      - PISTON_LOG_LEVEL=INFO
    volumes:
      - piston_data:/piston
    tmpfs:
      - /tmp:size=512m
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--quiet',
          '--tries=1',
          '--spider',
          'http://localhost:2000/api/v2/runtimes',
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - quiz-network

  piston-installer:
    image: node:alpine
    container_name: quiz-piston-installer
    depends_on:
      piston:
        condition: service_started
    command: >
      sh -c "
      echo 'Starting language installation...' && \
      apk add --no-cache git curl && \
      git clone https://github.com/engineer-man/piston.git /tmp/piston-cli && \
      cd /tmp/piston-cli/cli && \
      npm install && \
      echo 'Installing Node.js...' && \
      (node index.js -u http://piston:2000 ppman install node || echo 'Node.js install failed') && \
      echo 'Installing TypeScript...' && \
      (node index.js -u http://piston:2000 ppman install typescript || echo 'TypeScript install failed') && \
      echo 'Installing JavaScript...' && \
      (node index.js -u http://piston:2000 ppman install javascript || echo 'JavaScript install failed') && \
      echo 'Installing Python...' && \
      (node index.js -u http://piston:2000 ppman install python || echo 'Python install failed') && \
      echo 'Installing Java...' && \
      (node index.js -u http://piston:2000 ppman install java || echo 'Java install failed') && \
      echo 'Installing C++...' && \
      (node index.js -u http://piston:2000 ppman install c++ || echo 'C++ install failed') && \
      echo 'Installing C#...' && \
      (node index.js -u http://piston:2000 ppman install csharp || echo 'C# install failed') && \
      echo 'Installing Go...' && \
      (node index.js -u http://piston:2000 ppman install go || echo 'Go install failed') && \
      echo 'Installing Rust...' && \
      (node index.js -u http://piston:2000 ppman install rust || echo 'Rust install failed') && \
      echo 'Installing PHP...' && \
      (node index.js -u http://piston:2000 ppman install php || echo 'PHP install failed') && \
      echo 'Installing Ruby...' && \
      (node index.js -u http://piston:2000 ppman install ruby || echo 'Ruby install failed') && \
      rm -rf /tmp/piston-cli && \
      echo 'Language installation process completed!'
      "
    restart: 'no'
    networks:
      - quiz-network

  quiz-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quiz-frontend
    ports:
      - '3000:80'
    environment:
      - VITE_OLLAMA_URL=http://ollama:11434
      - VITE_PISTON_URL=http://piston:2000
    depends_on:
      ollama:
        condition: service_healthy
      piston:
        condition: service_started
    restart: unless-stopped
    networks:
      - quiz-network

networks:
  quiz-network:
    driver: bridge

volumes:
  ollama_data:
    driver: local
  piston_data:
    driver: local
