services:
  ollama:
    image: ollama/ollama:latest
    container_name: quiz-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 60s
      timeout: 30s
      retries: 10
      start_period: 300s

  quiz-app:
    build: .
    container_name: quiz-frontend
    ports:
      - "3000:80"
    environment:
      - VITE_OLLAMA_URL=http://ollama:11434
      - VITE_GEMINI_API_KEY=${VITE_GEMINI_API_KEY}
    depends_on:
      ollama:
        condition: service_healthy
    restart: unless-stopped

volumes:
  ollama_data:
    driver: local 