services:
  ollama:
    image: ollama/ollama:latest
    container_name: quiz-ollama
    ports:
      - '11434:11434'
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_NUM_PARALLEL=2
      - OLLAMA_MAX_LOADED_MODELS=1
      - OLLAMA_FLASH_ATTENTION=1
      - OLLAMA_GPU_LAYERS=999
      - OLLAMA_VRAM_FRACTION=0.8
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
          memory: 4G
    healthcheck:
      test: ['CMD', 'ollama', 'list']
      interval: 60s
      timeout: 30s
      retries: 10
      start_period: 300s
    networks:
      - quiz-network

  piston:
    image: ghcr.io/engineer-man/piston
    container_name: quiz-piston
    ports:
      - '2000:2000'
    restart: unless-stopped
    privileged: true
    environment:
      - PISTON_LOG_LEVEL=INFO
    volumes:
      - piston_data:/piston
    tmpfs:
      - /tmp:size=512m
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--quiet',
          '--tries=1',
          '--spider',
          'http://localhost:2000/api/v2/runtimes',
        ]
      interval: 60s
      timeout: 15s
      retries: 10
      start_period: 300s
    networks:
      - quiz-network

  piston-installer:
    image: node:alpine
    container_name: quiz-piston-installer
    depends_on:
      piston:
        condition: service_started
    volumes:
      - ./scripts:/scripts
    command: sh -c "apk add --no-cache bash && bash /scripts/piston-lang-init.sh"
    restart: 'no'
    networks:
      - quiz-network

  quiz-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quiz-frontend
    ports:
      - '3000:80'
    environment:
      - VITE_OLLAMA_URL=http://ollama:11434
      - VITE_PISTON_URL=http://piston:2000
    volumes:
      - frontend_build:/shared
    # depends_on:
    #   ollama:
    #     condition: service_started
    #   piston:
    #     condition: service_healthy
    restart: 'no'
    networks:
      - quiz-network

networks:
  quiz-network:
    driver: bridge

volumes:
  ollama_data:
    driver: local
  piston_data:
    driver: local
  frontend_build:
    driver: local
